

services:
  # Servicio de base de datos para usuarios
  mysql:
    image: mysql:8
    container_name: mysql-usuarios
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: usuarios
      MYSQL_USER: usuario
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql-usuarios-data:/var/lib/mysql

  # Microservicio de gestión de usuarios
  gestionusuarios:
    build: ./services/gestionUsuarios
    container_name: gestionusuarios
    restart: always
    env_file:
      - ./services/gestionUsuarios/.env
    ports:
      - "3001:3001"
    depends_on:
      - mysql    

  # Servicio de base de datos para inscripciones
  mysql3:
    image: mysql:8
    container_name: mysql-inscripciones
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: inscripciones_certificaciones
      MYSQL_USER: usuario
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
    volumes:
      - mysql-inscripciones-data:/var/lib/mysql

  # Microservicio de inscripciones y certificaciones
  inscripcionescertificaciones:
    build: ./services/iscripciones-certificaciones
    container_name: inscripcionescertificaciones
    restart: always
    env_file:
      - ./services/iscripciones-certificaciones/.env
    ports:
      - "3003:3003"
    depends_on:
      - mysql3    

volumes:
  mysql-usuarios-data:
  mysql-inscripciones-data:
