

services:
  # Servicio de base de datos para usuarios
  mysql:
    image: adrianvalvi/mysql-usuarios:con-datos
    container_name: mysql-usuarios
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: usuarios
      MYSQL_USER: usuario
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql-usuarios-data:/var/lib/mysql

  # Microservicio de gestión de usuarios
  gestionusuarios:
    image: adrianvalvi/gestionusuarios:latest
    container_name: gestionusuarios
    restart: always
    env_file:
      - ./services/gestionUsuarios/.env
    ports:
      - "3001:3001"
    depends_on:
      - mysql    

  #Micrcoservicio de gestión de talleres
  gestion-talleres:
    build: ./services/gestionTalleres
    container_name: gestion-talleres
    restart: always
    env_file:
      - ./services/gestionTalleres/.env
    ports:
      - "3002:3002"
    depends_on:
      - mysql2    
  
  # Servicio de base de datos para gestion de talleres
  mysql2: 
    image: mysql:8
    container_name: mysql-gestion-talleres
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: gestion-talleres
      MYSQL_USER: usuario
      MYSQL_PASSWORD: password
    ports:
      - "3309:3306"
    volumes:
      - mysql-gestion-talleres-data:/var/lib/mysql

  # Servicio de base de datos para inscripciones
  mysql3:
    image: mysql:8
    container_name: mysql-inscripciones
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: iscripciones-certificados
      MYSQL_USER: usuario
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
    volumes:
      - mysql-inscripciones-data:/var/lib/mysql

  # Microservicio de inscripciones y certificaciones
  inscripcionescertificaciones:
    build: ./services/iscripciones-certificaciones
    container_name: inscripcionescertificaciones
    restart: always
    env_file:
      - ./services/iscripciones-certificaciones/.env
    ports:
      - "3003:3003"
    depends_on:
      - mysql3    

volumes:
  mysql-usuarios-data:
  mysql-gestion-talleres-data:
  mysql-inscripciones-data:
