services:
  mysql:
    image: mysql:8
    container_name: mysql-usuarios
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: usuarios
      MYSQL_USER: usuario
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306" # Cambiar el puerto si el 3306 está ocupado el primer puerto es el de la máquina y el segundo el del contenedor
    volumes:
      - mysql-usuarios-data:/var/lib/mysql

volumes:
  mysql-usuarios-data:
